### ISSUE TITLE
Set up Travis automated builds

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FingerprintingBlocker#2]
@seanl-adg you'll need my help with this, please poke me when you're ready.

**Comment by theseanl** [comment]
It had been ready since the latest commit.

**Comment by ameshkov** [comment]
https://travis-ci.org/AdguardTeam/FingerprintingBlocker

**Comment by ameshkov** [comment]
Plz close this issue once we have the first successful build

**Comment by ameshkov** [comment]
Also add a travis image to readme plz

**Comment by ameshkov** [comment]
@seanl-adg add travis image to readme plz
