### ISSUE TITLE
Trigger log does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FingerprintingBlocker#3]
Steps to reproduce:

1. Open https://browserleaks.com/canvas
2. Click "details", then "trigger log"
3. An iframe will appear but the same webpage will be loaded inside of it

**Comment by theseanl** [comment]
It was just a stub, since we don't have any better idea for a detailed settings page, I will try to implement it into the alert iframe

**Comment by ameshkov** [comment]
Hm, what exactly would you like to print there?

Depending on that you should either have it inside of an iframe, or have it on the settings page.
