### ISSUE TITLE
The new fingerprint does not seem to be "random"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FingerprintingBlocker#4]
While testing it on https://browserleaks.com/canvas, I'm always getting the same FP.

I should be getting a new one every page reload.

**Comment by theseanl** [comment]
There will be settings for changing this behavior, a 'salt' renewal policy can be set to 'constant', 'per-domain', 'per-session', 'everytime'

**Comment by ameshkov** [comment]
Closed, let's discuss it in another issue then
https://github.com/AdguardTeam/FingerprintingBlocker/issues/6
